# fly.toml app configuration file generated for pm-base-blog-1 on 2024-03-16T09:52:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pm-base-blog-1'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

